### PR TITLE
Update datadog.sh

### PR DESCRIPTION
**Pull request by Yiyuan-Geng**
I believe -config parameter will be be deprecated, and replaced by --config

### CODE REVIEW

**Comment by Yiyuan-Geng** [comment]
https://datadog.zendesk.com/agent/tickets/1854295  

I have a customer who is using the heroku-buildpack, and seeing the warning message from output:
WARNING: `-config` argument is deprecated and will be removed in a future version. Please use `--config` instead.

image

**Review by arapulido — CHANGES_REQUESTED** [review]
Thanks for the change!

The buildpack is backwards compatible with previous versions of the Agent, so in order to accept this change, we would need to know the following:

* What version of the Agent introduced `--config`, as we would probably need to add some version comparison to ensure backwards compatibility (you can see an example of a similar check here: https://github.com/DataDog/heroku-buildpack-datadog/blob/2f197c9a5c099f9aaef08a7d39a7399bf06d35de/extra/datadog.sh#L361)
* What version would be `-config` completely removed?

**Comment by Yiyuan-Geng** [comment]
Hi team, please find my findings:

- From the agent change [log](https://github.com/DataDog/datadog-agent/blob/main/CHANGELOG.rst#7480--6480), I found this --config was introduced in the 7.48.

- There is no plan to remove it as of now, but we mention it in the changelog and the CLI because one day we might need/want to. It's good to know that some install methods still use the old version now (so it shouldn't be removed right now)

**Comment by arapulido** [comment]
We agreed to follow a different approach. Closing.

**Pull request closed without merging**
