### PR TITLE
Allow override of datadog config path

### PR DESCRIPTION
**Pull request by IanVaughan**
I would like to use a different path for the datadog config files.
I've added a env var DD_CONFIG that allows the user to change the default.
If DD_CONFIG is not set it will use the default as it was before.

### CODE REVIEW

**Comment by IanVaughan** [comment]
Hi, yep, sorry for missing that...
Our Rails app follows the standard CoC folder setup, adding a `datadog` folder in the mix is confusing.
Also, we follow a standard for system/devop/config files using a dot folder, eg `.github`, and hopefully `.datadog`.
With this change, we, and others, can keep system config hidden from normal day to day development.

**Review by arapulido — CHANGES_REQUESTED** [review]
Thanks @IanVaughan I think the change makes sense, but it would be great if you could make some improvements before we merge this.

I think DD_CONFIG is not the best name for the variable, can we change it to something like `DD_HEROKU_CONF_FOLDER` ?

Also, we would need some documentation about this option in the configuration section of the readme: https://github.com/DataDog/heroku-buildpack-datadog/blob/master/README.md#configuration

Bonus points: there are a couple of references to the `/datadog` folder in the README (in the "enable integrations", and the "prerun script" sections, that will need an update.

Thanks!

**Comment by IanVaughan** [comment]
> I think DD_CONFIG is not the best name for the variable, can we change it to something like `DD_HEROKU_CONF_FOLDER`

- [ ] Yes sure, that's a much better name.

> Also, we would need some documentation about this option in the configuration section of the readme: https://github.com/DataDog/heroku-buildpack-datadog/blob/master/README.md#configuration

- [ ] Sure, I'll add something there

>  update references to the `/datadog` folder in the README

- [ ] Update references.


I'll ping back when all updated, cheers.

**Comment by IanVaughan** [comment]
@arapulido

> Bonus points: there are a couple of references to the `/datadog` folder in the README (in the "enable integrations", and the "prerun script" sections, that will need an update.

Do you think they should be updated? As what should they be changed to?
```diff
-create the file /datadog/conf.d/redisdb.yaml 
+create the file /$DD_HEROKU_CONF_FOLDER/conf.d/redisdb.yaml 
```
This seems to imply that `DD_HEROKU_CONF_FOLDER` has to be set.
Or did you have another idea?

**Comment by IanVaughan** [comment]
Other changes make, cheers.

**Comment by arapulido** [comment]
> @arapulido
> 
> > Bonus points: there are a couple of references to the `/datadog` folder in the README (in the "enable integrations", and the "prerun script" sections, that will need an update.
> 
> Do you think they should be updated? As what should they be changed to?
> 
> ```diff
> -create the file /datadog/conf.d/redisdb.yaml 
> +create the file /$DD_HEROKU_CONF_FOLDER/conf.d/redisdb.yaml 
> ```
> 
> This seems to imply that `DD_HEROKU_CONF_FOLDER` has to be set.
> Or did you have another idea?

Maybe something like:

```diff
-create the file /datadog/conf.d/redisdb.yaml 
+create the file /datadog/conf.d/redisdb.yaml  (or /$DD_HEROKU_CONF_FOLDER/conf.d/redisdb.yaml if you have changed this [configuration option](#configuration))
```

**Comment by arapulido** [comment]
> Other changes make, cheers.

Awesome, thanks! I made a suggestion on the other change

**Comment by IanVaughan** [comment]
Ok, I've made a slight change, hope it looks good, just say if you have better ideas! Cheers

**Review by arapulido — APPROVED** [review]
Great, thanks! I will approve and merge now 🎉 

Thanks again for your contribution! Very much appreciated 😃

**Pull request merged**
