### PR TITLE
Add embedded lib dir to LD_LIBRARY_PATH in datadog.sh

### LINKED ISSUE #126: Error and command "start" is deprecated log messages on startup
I'm seeing these log messages on every dyno that starts with this buildpack enabled:

```
/app/.apt/opt/datadog-agent/bin/agent/agent: error while loading shared libraries: libdatadog-agent-rtloader.so.1: cannot open shared object file: No such file or directory
Starting Datadog Agent on 4b572819-...-....-....-............
Starting Datadog Trace Agent on 4b572819-...-....-....-............
Command "start" is deprecated, Use "run" instead to start the Agent
```

I believe the first error is from the version command @ https://github.com/DataDog/heroku-buildpack-datadog/blob/1f3d13dbbe873f12075075136fd9c26362243efc/extra/datadog.sh#L128

Then the message `start` comes because the version check didn't determine the agent is > 6.4.1 

It looks like the `LD_LIBRARY_PATH` env var needs setting for the version check too. If I `heroku run` to get a bash dyno, and run this, it succeeds:

```
~ $ export LD_LIBRARY_PATH="/app/.apt/opt/datadog-agent/embedded/lib:$LD_LIBRARY_PATH"
~ $ /app/.apt/opt/datadog-agent/bin/agent/agent version
Agent 6.13.0 - Commit: df8e880 - Serialization version: 4.7.1 - Go version: go1.11.5
```

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #126.

### CODE REVIEW

**Comment by adamchainz** [comment]
I'm not able to test this in with the environment I'm seeing the breakage in, but I believe this is the fix.

**Comment by adamchainz** [comment]
Please can you take over? I don't have time to work on this

**Comment by arapulido** [comment]
Sure, I will take over. Thanks again!

**Comment by arapulido** [comment]
Closing this PR, and will open a new one.

**Pull request closed without merging**
