### PR TITLE
Allow to set DD_TAGS in prerun

### PR DESCRIPTION
**Pull request by jd**
Currently it's impossible to dynamically set tags via the prerun script.

### CODE REVIEW

**Comment by jd** [comment]
I did not test it so someone should make sure it does not break anything.

**Comment by arapulido** [comment]
Thanks for the PR! We will be reviewing this in the next few days

**Comment by arapulido** [comment]
We cannot merge this as is, as I think it may cause this issue: https://github.com/DataDog/heroku-buildpack-datadog/issues/102 

I will work on revamping how we parse and deal with tags in the buildpack so your use case is taken  into account, without breaking existing functionality.

**Comment by jd** [comment]
I don't think this PR will cause #102 that already exists, but for sure it won't fix it. :)

If you want to fix both issues with a refactor, that'll work for me. Let me know if you need help! 👍

**Comment by arapulido** [comment]
sorry, I meant https://github.com/DataDog/heroku-buildpack-datadog/issues/109

**Comment by arapulido** [comment]
@jd I am going to close this PR for now. Once I work on improving tag handling for the buildpack I will let you know to see how we can incorporate your suggestion. Thanks!

**Pull request closed without merging**
